local hit_effects = require("__base__/prototypes/entity/hit-effects")
local sounds = require("__base__/prototypes/entity/sounds")

circuit_connector_definitions["cube-big-container"] = circuit_connector_definitions.create(universal_connector_template, {
  {
    variation = 26,
    main_offset = util.by_pixel(0.5, -2.6),
    shadow_offset = util.by_pixel(3.5, 0),
    show_shadow = true,
  },
})

data:extend({
  {
    type = "container",
    name = "cube-medium-container",
    icon = "__Krastorio2Assets__/icons/entities/containers/medium-containers/medium-container.png",
    icon_size = 64,
    icon_mipmaps = 4,
    flags = {"placeable-player", "player-creation", "not-rotatable"},
    minable = {mining_time = 0.5, result = "cube-medium-container"},
    max_health = 500,
    corpse = "big-remnants",
    collision_box = {{-0.8, -0.8}, {0.8, 0.8}},
    selection_box = {{-1, -1}, {1, 1}},
    damaged_trigger_effect = hit_effects.entity(),
    fast_replaceable_group = "container",
    inventory_size = 40,
    scale_info_icons = true,
    vehicle_impact_sound = sounds.generic_impact,
    opened_duration = logistic_chest_opened_duration,
    picture = {
      filename = "__Krastorio2Assets__/entities/containers/medium-containers/medium-container/medium-container.png",
      priority = "extra-high",
      width = 85,
      height = 85,
      hr_version = {
        filename = "__Krastorio2Assets__/entities/containers/medium-containers/medium-container/hr-medium-container.png",
        priority = "extra-high",
        width = 340,
        height = 340,
        scale = 0.25,
      },
    },
    circuit_wire_connection_point = circuit_connector_definitions["chest"].points,
    circuit_connector_sprites = circuit_connector_definitions["chest"].sprites,
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    open_sound = sounds.machine_open,
    close_sound = sounds.machine_close,
  },
  {
    type = "container",
    name = "cube-big-container",
    icon = "__Krastorio2Assets__/icons/entities/containers/big-containers/big-container.png",
    icon_size = 64,
    icon_mipmaps = 4,
    flags = {"placeable-player", "player-creation", "not-rotatable"},
    minable = {mining_time = 1, result = "cube-big-container"},
    max_health = 1500,
    corpse = "cube-big-random-pipes-remnant",
    collision_box = {{-1.25, -1.25}, {1.25, 1.25}},
    selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
    damaged_trigger_effect = hit_effects.entity(),
    fast_replaceable_group = "container",
    inventory_size = 60,
    scale_info_icons = true,
    vehicle_impact_sound = sounds.generic_impact,
    opened_duration = logistic_chest_opened_duration,
    picture = {
      filename = "__Krastorio2Assets__/entities/containers/big-containers/big-container/big-container.png",
      priority = "extra-high",
      width = 213,
      height = 213,
      scale = 0.6,
      hr_version = {
        filename = "__Krastorio2Assets__/entities/containers/big-containers/big-container/hr-big-container.png",
        priority = "extra-high",
        width = 512,
        height = 512,
        scale = 0.25,
      },
    },

    water_reflection = {
      pictures = {
        filename = "__Krastorio2Assets__/entities/containers/big-containers/big-container-reflection.png",
        priority = "extra-high",
        width = 60,
        height = 50,
        shift = util.by_pixel(0, 20),
        variation_count = 1,
        scale = 2.5,
      },
      rotate = false,
      orientation_to_variation = false,
    },

    circuit_wire_connection_point = circuit_connector_definitions["cube-big-container"].points,
    circuit_connector_sprites = circuit_connector_definitions["cube-big-container"].sprites,
    circuit_wire_max_distance = 20,
    open_sound = sounds.machine_open,
    close_sound = sounds.machine_close,
  },
})