local hit_effects = require("__base__/prototypes/entity/hit-effects")
local sounds = require("__base__/prototypes/entity/sounds")

local teleporter_animation = {
  layers = {
    {
      filename = "__Krastorio2Assets__/entities/planetary-teleporter/hr-planetary-teleporter-shadow.png",
      priority = "low",
      width = 531,
      height = 292,
      scale = 0.5,
      frame_count = 1,
      repeat_count = 20,
      draw_as_shadow = true,
      animation_speed = 0.5,
      shift = {1.9, 1.2},
    },
    {
      filename = "__Krastorio2Assets__/entities/planetary-teleporter/new/hr-teleporter-base-combined.png",
      priority = "medium",
      width = 400,
      height = 475,
      scale = 0.5,
      frame_count = 20,
      line_length = 5,
      animation_speed = 0.5,
    },
    {
      filename = "__Krastorio2Assets__/entities/planetary-teleporter/new/hr-teleporter-under-forward-towers.png",
      priority = "medium",
      width = 400,
      height = 475,
      scale = 0.5,
      repeat_count = 20,
      animation_speed = 0.5,
    },
    {
      filename = "__Krastorio2Assets__/entities/planetary-teleporter/new/hr-teleporter-base-combined-glow.png",
      priority = "high",
      width = 400,
      height = 475,
      scale = 0.5,
      frame_count = 20,
      line_length = 5,
      animation_speed = 0.5,
      draw_as_glow = true,
      fadeout = true,
      blend_mode = "additive-soft",
    },
    {
      filename = "__Krastorio2Assets__/entities/planetary-teleporter/new/hr-teleporter-base-combined-glow.png",
      priority = "extra-high",
      width = 400,
      height = 475,
      scale = 0.5,
      frame_count = 20,
      line_length = 5,
      animation_speed = 0.5,
      draw_as_light = true,
      blend_mode = "additive-soft",
    },
    {
      filename = "__Krastorio2Assets__/entities/planetary-teleporter/new/hr-teleporter-forward-towers-light.png",
      priority = "extra-high",
      width = 400,
      height = 475,
      scale = 0.5,
      frame_count = 20,
      line_length = 5,
      animation_speed = 0.5,
    },
  },
}

local teleporter_animation_red = {
  layers = {
    {
      filename = "__Krastorio2Assets__/entities/planetary-teleporter/hr-planetary-teleporter-shadow.png",
      priority = "low",
      width = 531,
      height = 292,
      scale = 0.5,
      frame_count = 1,
      repeat_count = 20,
      draw_as_shadow = true,
      animation_speed = 0.5,
      shift = {1.9, 1.2},
    },
    {
      filename = "__Krastorio2Assets__/entities/planetary-teleporter/new/hr-teleporter-base-combined.png",
      priority = "medium",
      width = 400,
      height = 475,
      scale = 0.5,
      frame_count = 20,
      line_length = 5,
      animation_speed = 0.5,
    },
    {
      filename = "__Krastorio2Assets__/entities/planetary-teleporter/new/hr-teleporter-under-forward-towers.png",
      priority = "medium",
      width = 400,
      height = 475,
      scale = 0.5,
      repeat_count = 20,
      animation_speed = 0.5,
    },
    {
      filename = "__Krastorio2Assets__/entities/planetary-teleporter/new/hr-teleporter-base-combined-glow-red.png",
      flags = {"mask"},
      priority = "extra-high",
      width = 400,
      height = 475,
      scale = 0.5,
      frame_count = 20,
      line_length = 5,
      animation_speed = 0.5,
      apply_runtime_tint = true,
      tint = {r = 1, g = 0, b = 0, a = 1},
    },
    {
      filename = "__Krastorio2Assets__/entities/planetary-teleporter/new/hr-teleporter-base-combined-glow-red.png",
      priority = "high",
      width = 400,
      height = 475,
      scale = 0.5,
      frame_count = 20,
      line_length = 5,
      animation_speed = 0.5,
      draw_as_glow = true,
      fadeout = true,
      blend_mode = "additive-soft",
    },
    {
      filename = "__Krastorio2Assets__/entities/planetary-teleporter/new/hr-teleporter-base-combined-glow-red.png",
      priority = "extra-high",
      width = 400,
      height = 475,
      scale = 0.5,
      frame_count = 20,
      line_length = 5,
      animation_speed = 0.5,
      draw_as_light = true,
      blend_mode = "additive-soft",
    },
    {
      filename = "__Krastorio2Assets__/entities/planetary-teleporter/new/hr-teleporter-forward-towers-light.png",
      priority = "extra-high",
      width = 400,
      height = 475,
      scale = 0.5,
      frame_count = 20,
      line_length = 5,
      animation_speed = 0.5,
    },
  },
}

data:extend({
  {
    type = "accumulator",
    name = "cube-experimental-teleporter",
    icon = "__Krastorio2Assets__/icons/entities/planetary-teleporter.png",
    icon_size = 64,
    icon_mipmaps = 4,
    flags = {"placeable-neutral", "placeable-player", "player-creation", "not-rotatable"},
    map_color = {r = 0.337, g = 0.011, b = 0.184},
    max_health = 2000,
    minable = {mining_time = 2, result = "cube-experimental-teleporter"},
    corpse = "big-remnants",
    dying_explosion = "big-explosion",
    damaged_trigger_effect = hit_effects.entity(),
    collision_box = {{-2.65, -1.9}, {2.65, 3.2}},
    selection_box = {{-3, -2}, {3, 3.4}},
    drawing_box = {{-3, -3}, {3, 3}},
    energy_source = {
      type = "electric",
      buffer_capacity = "400MJ",
      input_flow_limit = "20MW",
      usage_priority = "tertiary",
      output_flow_limit = "0W",
    },
    picture = teleporter_animation,
    charge_animation = teleporter_animation_red,
    charge_cooldown = 10,
    discharge_cooldown = 10,
    vehicle_impact_sound = sounds.generic_impact,
    working_sound = {
      sound = {
        filename = "__Krastorio2Assets__/sounds/buildings/planetary-teleporter-working-sound.ogg",
        volume = 0.50,
      },
      idle_sound = {filename = "__base__/sound/idle1.ogg"},
      apparent_volume = 0.75,
    },
    open_sound = {filename = "__Krastorio2Assets__/sounds/buildings/planetary-teleporter-open-sound.ogg", volume = 1},
    close_sound = {filename = "__Krastorio2Assets__/sounds/buildings/planetary-teleporter-close-sound.ogg", volume = 0.8},
    audible_distance_modifier = 30,
    circuit_wire_connection_point = nil, --circuit_connector_definitions["accumulator"].points,
    circuit_connector_sprites = nil, --circuit_connector_definitions["accumulator"].sprites,
    circuit_wire_max_distance = 0, --default_circuit_wire_max_distance,
    default_output_signal = {type = "virtual", name = "signal-P"},
  },
})
