data:extend({
  {
    type = "item",
    name = "cube-boiler",
    icon = "__base__/graphics/icons/boiler.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "energy",
    order = "b[steam-power]-a[boiler]",
    place_result = "cube-boiler",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-lab",
    icon = "__base__/graphics/icons/lab.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "g[lab]",
    place_result = "cube-lab",
    stack_size = 10
  },
  {
    type = "item",
    name = "cube-charger",
    icon = "__Krastorio2Assets__/icons/entities/stabilizer-charging-station.png",
    icon_size = 128,
    icon_mipmaps = 4,
    subgroup = "cube-production-machines",
    order = "0[0-charger]",
    place_result = "cube-charger",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-synthesizer",
    icon = "__Krastorio2Assets__/icons/entities/matter-assembler.png",
    icon_size = 128,
    icon_mipmaps = 4,
    subgroup = "cube-production-machines",
    order = "0[1-synthesizer]",
    place_result = "cube-synthesizer",
    stack_size = 10,
  },
})
