data:extend({
  {
    type = "item",
    name = "cube-boiler",
    icon = "__base__/graphics/icons/boiler.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "energy",
    order = "b[steam-power]-a[boiler]",
    place_result = "cube-boiler",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-lab",
    icon = "__Krastorio2Assets__/icons/entities/biusart-lab.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-logistic-machines",
    order = "0[lab]",
    place_result = "cube-lab",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-electric-mining-drill",
    icon = "__Krastorio2Assets__/icons/entities/electric-mining-drill-mk2.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "extraction-machine",
    order = "d[0-drill-1]",
    place_result = "cube-electric-mining-drill",
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-electric-mining-drill-mk2",
    icon = "__Krastorio2Assets__/icons/entities/electric-mining-drill-mk3.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "extraction-machine",
    order = "d[0-drill-2]",
    place_result = "cube-electric-mining-drill-mk2",
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-electric-mining-drill-mk2",
    icon = "__Krastorio2Assets__/icons/entities/electric-mining-drill-mk3.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "extraction-machine",
    order = "d[0-drill-2]",
    place_result = "cube-electric-mining-drill-mk2",
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-deep-core-ultradrill",
    icon = "__Krastorio2Assets__/icons/entities/quarry-drill.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "extraction-machine",
    order = "x[0-deep-drill-1]",
    place_result = "cube-deep-core-ultradrill",
    stack_size = 5,
  },
  {
    type = "item",
    name = "cube-greenhouse",
    icon = "__Krastorio2Assets__/icons/entities/greenhouse.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "extraction-machine",
    order = "c[0-greenhouse]",
    place_result = "cube-greenhouse",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-crusher",
    icon = "__Krastorio2Assets__/icons/entities/crusher.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-processing-machines",
    order = "0[0-crusher]",
    place_result = "cube-crusher",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-electric-furnace",
    icon = "__base__/graphics/icons/electric-furnace.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-processing-machines",
    order = "0[1-electric-furnace]",
    place_result = "cube-electric-furnace",
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-chemical-plant",
    icon = "__base__/graphics/icons/chemical-plant.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-chemical-machines",
    order = "1[0-chemical-plant]",
    place_result = "cube-chemical-plant",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-distillery",
    icon = "__base__/graphics/icons/oil-refinery.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-chemical-machines",
    order = "1[1-distillery]",
    place_result = "cube-distillery",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-fuel-refinery",
    icon = "__Krastorio2Assets__/icons/entities/fuel-refinery.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-chemical-machines",
    order = "1[2-fuel-refinery]",
    place_result = "cube-fuel-refinery",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-fluid-burner",
    icon = "__Krastorio2Assets__/icons/entities/fluid-burner.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-chemical-machines",
    order = "1[3-fluid-burner]",
    place_result = "cube-fluid-burner",
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-ultradense-furnace",
    icon = "__Krastorio2Assets__/icons/entities/advanced-furnace.png",
    icon_size = 128, icon_mipmaps = 4,
    subgroup = "cube-processing-machines",
    order = "0[2-ultradense-furace]",
    place_result = "cube-ultradense-furnace",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-recovery-bay",
    icon = "__Krastorio2Assets__/icons/entities/stabilizer-charging-station.png",
    icon_size = 128, icon_mipmaps = 4,
    subgroup = "cube-production-machines",
    order = "1[0-recovery-bay]",
    place_result = "cube-recovery-bay",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-synthesizer",
    icon = "__Krastorio2Assets__/icons/entities/matter-assembler.png",
    icon_size = 128, icon_mipmaps = 4,
    subgroup = "cube-production-machines",
    order = "1[1-synthesizer]",
    place_result = "cube-synthesizer",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-dimension-folding-engine",
    icon = "__Krastorio2Assets__/icons/entities/antimatter-reactor.png",
    icon_size = 128, icon_mipmaps = 4,
    subgroup = "cube-production-machines",
    order = "1[2-disruptor]",
    place_result = "cube-dimension-folding-engine",
    stack_size = 5,
  },
  {
    type = "item",
    name = "cube-stygian-energy-lab",
    icon = "__Krastorio2Assets__/icons/entities/bio-lab.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-advanced-power",
    order = "x[0-haunted]",
    place_result = "cube-stygian-energy-lab",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-heavy-turbine",
    icon = "__base__/graphics/icons/steam-turbine.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "energy",
    order = "b[steam-power]-c[heavy-turbine]",
    place_result = "cube-heavy-turbine",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-fabricator",
    icon = "__Krastorio2Assets__/icons/entities/advanced-assembling-machine.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-production-machines",
    order = "1[3-fabricator]",
    place_result = "cube-fabricator",
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-roboport",
    icon = "__Krastorio2Assets__/icons/entities/large-roboport.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "cube-logistic-machines",
    order = "2[roboport]",
    place_result = "cube-roboport",
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-energy-bulkframe",
    icon = "__Krastorio2Assets__/icons/entities/energy-storage.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "energy",
    order = "z[energy-frame]",
    place_result = "cube-energy-bulkframe",
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-nuclear-reactor",
    icon = "__base__/graphics/icons/nuclear-reactor.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-advanced-power",
    order = "f[nuclear-energy]-a[reactor]",
    place_result = "cube-nuclear-reactor",
    stack_size = 5,
  },
  {
    type = "item",
    name = "cube-cyclotron",
    icon = "__Krastorio2Assets__/icons/entities/matter-plant.png",
    icon_size = 128, icon_mipmaps = 4,
    subgroup = "cube-advanced-machines",
    order = "a[decoder]",
    place_result = "cube-cyclotron",
    stack_size = 5,
  },
  {
    type = "item",
    name = "cube-quantum-decoder",
    icon = "__Krastorio2Assets__/icons/entities/quantum-computer.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-advanced-machines",
    order = "b[decoder]",
    place_result = "cube-quantum-decoder",
    stack_size = 5,
  },
  {
    type = "item",
    name = "cube-particle-phase-aligner",
    icon = "__Krastorio2Assets__/icons/entities/research-server.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-advanced-machines",
    order = "c[aligner]",
    place_result = "cube-particle-phase-aligner",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-mystery-furnace",
    icon = "__base__/graphics/icons/steel-furnace.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-advanced-machines",
    order = "d[mystery]",
    place_result = "cube-mystery-furnace",
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-beacon",
    icon = "__Krastorio2Assets__/icons/entities/singularity-beacon.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-logistic-machines",
    order = "3[beacon]",
    place_result = "cube-beacon",
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-experimental-teleporter",
    icon = "__Krastorio2Assets__/icons/entities/planetary-teleporter.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-logistic-machines",
    order = "4[teleporter]",
    place_result = "cube-experimental-teleporter",
    stack_size = 5,
  },
  {
    type = "item",
    name = "cube-forbidden-ziggurat",
    icon = "__Krastorio2Assets__/icons/entities/intergalactic-transceiver.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-final-machines",
    order = "0[ziggurat]",
    place_result = "cube-forbidden-ziggurat",
    stack_size = 1,
    flags = {"not-stackable"},
  },
  {
    type = "item",
    name = "cube-antimatter-reactor",
    icon = "__Krastorio2Assets__/icons/entities/fusion-reactor.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-final-machines",
    order = "1[reactor]",
    place_result = "cube-antimatter-reactor",
    stack_size = 1,
    flags = {"not-stackable"},
  },
  {
    type = "item",
    name = "cube-annihilation-chamber",
    icon = "__Krastorio2Assets__/icons/entities/advanced-steam-turbine.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-final-machines",
    order = "2[chamber]",
    place_result = "cube-annihilation-chamber",
    stack_size = 5,
  },
})
