data:extend({
  {
    type = "armor",
    name = "cube-modular-armor",
    icon = "__base__/graphics/icons/modular-armor.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "armor",
    order = "c[modular-armor]",
    stack_size = 1,
    infinite = true,
    equipment_grid = "cube-small-equipment-grid",
    resistances = {},
    inventory_size_bonus = 0,
    open_sound = {filename =  "__base__/sound/armor-open.ogg", volume = 1},
    close_sound = {filename = "__base__/sound/armor-close.ogg", volume = 1},
  },
  {
    type = "item",
    name = "cube-solar-panel-equipment",
    icon = "__base__/graphics/icons/solar-panel-equipment.png",
    icon_size = 64, icon_mipmaps = 4,
    placed_as_equipment_result = "cube-solar-panel-equipment",
    subgroup = "cube-equipment-power",
    order = "a[energy-source]-a[solar-panel]",
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-solar-panel-equipment-mk2",
    icon = "__Krastorio2Assets__/icons/entities/advanced-solar-panel.png",
    icon_size = 64, icon_mipmaps = 4,
    placed_as_equipment_result = "cube-solar-panel-equipment-mk2",
    subgroup = "cube-equipment-power",
    order = "a[energy-source]-b[solar-panel-mk2]",
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-battery-equipment",
    icon = "__base__/graphics/icons/battery-equipment.png",
    icon_size = 64, icon_mipmaps = 4,
    placed_as_equipment_result = "cube-battery-equipment",
    subgroup = "cube-equipment-power",
    order = "b[battery]-a[battery-equipment]",
    default_request_amount = 5,
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-personal-roboport-equipment",
    icon = "__base__/graphics/icons/personal-roboport-equipment.png",
    icon_size = 64, icon_mipmaps = 4,
    placed_as_equipment_result = "cube-personal-roboport-equipment",
    subgroup = "cube-equipment",
    order = "e[robotics]-a[personal-roboport-equipment]",
    default_request_amount = 1,
    stack_size = 20,
  },
})
