data:extend({
  {
    type = "item",
    name = "cube-boiler",
    icon = "__base__/graphics/icons/boiler.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "energy",
    order = "b[steam-power]-a[boiler]",
    place_result = "cube-boiler",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-lab",
    icon = "__Krastorio2Assets__/icons/entities/biusart-lab.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "production-machine",
    order = "g[lab]",
    place_result = "cube-lab",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-electric-mining-drill",
    icon = "__Krastorio2Assets__/icons/entities/electric-mining-drill-mk2.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "extraction-machine",
    order = "c[0-drill-1]",
    place_result = "cube-electric-mining-drill",
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-electric-mining-drill-mk2",
    icon = "__Krastorio2Assets__/icons/entities/electric-mining-drill-mk3.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "extraction-machine",
    order = "c[0-drill-2]",
    place_result = "cube-electric-mining-drill-mk2",
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-crusher",
    icon = "__Krastorio2Assets__/icons/entities/crusher.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "cube-processing-machines",
    order = "0[0-crusher]",
    place_result = "cube-crusher",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-electric-furnace",
    icon = "__base__/graphics/icons/electric-furnace.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-processing-machines",
    order = "0[1-electric-furnace]",
    place_result = "cube-electric-furnace",
    stack_size = 20,
  },
  {
    type = "item",
    name = "cube-chemical-plant",
    icon = "__base__/graphics/icons/chemical-plant.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-processing-machines",
    order = "1[0-chemical-plant]",
    place_result = "cube-chemical-plant",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-ultradense-furnace",
    icon = "__Krastorio2Assets__/icons/entities/advanced-furnace.png",
    icon_size = 128,
    icon_mipmaps = 4,
    subgroup = "cube-processing-machines",
    order = "0[2-ultradense-furace]",
    place_result = "cube-ultradense-furnace",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-recovery-bay",
    icon = "__Krastorio2Assets__/icons/entities/stabilizer-charging-station.png",
    icon_size = 128,
    icon_mipmaps = 4,
    subgroup = "cube-production-machines",
    order = "1[0-recovery-bay]",
    place_result = "cube-recovery-bay",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-synthesizer",
    icon = "__Krastorio2Assets__/icons/entities/matter-assembler.png",
    icon_size = 128,
    icon_mipmaps = 4,
    subgroup = "cube-production-machines",
    order = "1[1-synthesizer]",
    place_result = "cube-synthesizer",
    stack_size = 10,
  },
  {
    type = "item",
    name = "cube-fabricator",
    icon = "__Krastorio2Assets__/icons/entities/advanced-assembling-machine.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "cube-production-machines",
    order = "1[2-fabricator]",
    place_result = "cube-fabricator",
    stack_size = 20,
  }
})
