data:extend({
  {
    type = "tool",
    name = "cube-basic-contemplation-unit",
    localised_description = {"item-description.cube-science-card"},
    icon = "__Krastorio2Assets__/icons/cards/military-tech-card.png",
    icon_size = 64, icon_mipmaps = 4,
    pictures = {
      layers = {
        {
          size = 64,
          filename = "__Krastorio2Assets__/icons/cards/military-tech-card.png",
          scale = 0.25,
          mipmap_count = 4,
        },
        {
          draw_as_light = true,
          flags = {"light"},
          size = 64,
          filename = "__Krastorio2Assets__/icons/cards/military-tech-card-light.png",
          scale = 0.25,
          mipmap_count = 4,
        },
      },
    },
    subgroup = "cube-science",
    order = "cube-0[contemplation]",
    stack_size = 100,
    durability = 1,
  },
  {
    type = "tool",
    name = "cube-fundamental-comprehension-card",
    localised_description = {"item-description.cube-science-card"},
    icon = "__Krastorio2Assets__/icons/cards/logistic-tech-card.png",
    icon_size = 64, icon_mipmaps = 4,
    pictures = {
      layers = {
        {
          size = 64,
          filename = "__Krastorio2Assets__/icons/cards/logistic-tech-card.png",
          scale = 0.25,
          mipmap_count = 4,
        },
        {
          draw_as_light = true,
          flags = { "light" },
          size = 64,
          filename = "__Krastorio2Assets__/icons/cards/logistic-tech-card-light.png",
          scale = 0.25,
          mipmap_count = 4,
        },
      },
    },
    subgroup = "cube-science",
    order = "cube-1[comprehension]",
    stack_size = 100,
    durability = 1,
  },
  {
    type = "tool",
    name = "cube-abstract-interrogation-card",
    localised_description = {"item-description.cube-science-card"},
    icon = "__Krastorio2Assets__/icons/cards/matter-tech-card.png",
    icon_size = 64, icon_mipmaps = 4,
    pictures = {
      layers = {
        {
          size = 64,
          filename = "__Krastorio2Assets__/icons/cards/matter-tech-card.png",
          scale = 0.25,
          mipmap_count = 4,
        },
        {
          draw_as_light = true,
          flags = { "light" },
          size = 64,
          filename = "__Krastorio2Assets__/icons/cards/matter-tech-card-light.png",
          scale = 0.25,
          mipmap_count = 4,
        },
      },
    },
    subgroup = "cube-science",
    order = "cube-2[interrogation]",
    stack_size = 100,
    durability = 1,
  },
  {
    type = "tool",
    name = "cube-deep-introspection-card",
    localised_description = {"item-description.cube-science-card"},
    icon = "__Krastorio2Assets__/icons/cards/singularity-tech-card.png",
    icon_size = 64, icon_mipmaps = 4,
    pictures = {
      layers = {
        {
          size = 64,
          filename = "__Krastorio2Assets__/icons/cards/singularity-tech-card.png",
          scale = 0.25,
          mipmap_count = 4,
        },
        {
          draw_as_light = true,
          flags = {"light"},
          size = 64,
          filename = "__Krastorio2Assets__/icons/cards/singularity-tech-card-light.png",
          scale = 0.25,
          mipmap_count = 4,
        },
      },
    },
    subgroup = "cube-science",
    order = "cube-3[introspection]",
    stack_size = 100,
    durability = 1,
  },
  {
    type = "tool",
    name = "cube-synthetic-premonition-card",
    localised_description = {"item-description.cube-science-card"},
    icon = "__Krastorio2Assets__/icons/cards/optimization-tech-card.png",
    icon_size = 64, icon_mipmaps = 4,
    pictures = {
      layers = {
        {
          size = 64,
          filename = "__Krastorio2Assets__/icons/cards/optimization-tech-card.png",
          scale = 0.25,
          mipmap_count = 4,
        },
        {
          draw_as_light = true,
          flags = {"light"},
          size = 64,
          filename = "__Krastorio2Assets__/icons/cards/optimization-tech-card-light.png",
          scale = 0.25,
          mipmap_count = 4,
        },
      },
    },
    subgroup = "cube-science",
    order = "cube-4[premonition]",
    stack_size = 100,
    durability = 1,
  },
  {
    type = "tool",
    name = "cube-complete-annihilation-card",
    localised_description = {"item-description.cube-science-card"},
    icon = "__Krastorio2Assets__/icons/cards/advanced-tech-card.png",
    icon_size = 64, icon_mipmaps = 4,
    pictures = {
      layers = {
        {
          size = 64,
          filename = "__Krastorio2Assets__/icons/cards/advanced-tech-card.png",
          scale = 0.25,
          mipmap_count = 4,
        },
        {
          draw_as_light = true,
          flags = {"light"},
          size = 64,
          filename = "__Krastorio2Assets__/icons/cards/advanced-tech-card-light.png",
          scale = 0.25,
          mipmap_count = 4,
        },
      },
    },
    subgroup = "cube-science",
    order = "cube-5[annihilation]",
    stack_size = 100,
    durability = 1,
  },

  {
    type = "item",
    name = "cube-quantum-research-data",
    icon = "__Krastorio2Assets__/icons/cards/biters-research-data.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "cube-experimental",
    order = "cube-z[quantum-research-data]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "cube-singularity-research-data",
    icon = "__Krastorio2Assets__/icons/cards/singularity-research-data.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "cube-experimental",
    order = "cube-y[singularity-research-data]",
    stack_size = 50,
  },
  {
    type = "tool",
    name = "cube-construct-forbidden-ziggurat-dummy",
    icon = "__Krastorio2Assets__/icons/entities/intergalactic-transceiver.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "cube-final-machines",
    order = "cube-z[construct]",
    stack_size = 1,
    flags = {"hidden"},
    durability = 1,
  },
})
