data:extend({
  {
    type = "item",
    name = "cube-raw-rare-metals",
    icon = "__Krastorio2Assets__/icons/items-with-variations/raw-rare-metals/raw-rare-metals.png",
    icon_size = 64,
    icon_mipmaps = 4,
    pictures = {
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/raw-rare-metals/raw-rare-metals.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/raw-rare-metals/raw-rare-metals-1.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/raw-rare-metals/raw-rare-metals-2.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/raw-rare-metals/raw-rare-metals-3.png",
        scale = 0.25,
        mipmap_count = 4,
      },
    },
    subgroup = "raw-resource",
    order = "c[0-raw-rare-metals]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "cube-refined-rare-metals",
    icon = "__Krastorio2Assets__/icons/items-with-variations/enriched-rare-metals/enriched-rare-metals.png",
    icon_size = 64,
    icon_mipmaps = 4,
    pictures = {
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/enriched-rare-metals/enriched-rare-metals.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/enriched-rare-metals/enriched-rare-metals-1.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/enriched-rare-metals/enriched-rare-metals-2.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/raw-rare-metals/raw-rare-metals-3.png",
        scale = 0.25,
        mipmap_count = 4,
      },
    },
    subgroup = "raw-resource",
    order = "c[1-refined-rare-metals]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "cube-rare-metals",
    icon = "__Krastorio2Assets__/icons/items-with-variations/rare-metals/rare-metals.png",
    icon_size = 64,
    icon_mipmaps = 4,
    pictures = {
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/rare-metals/rare-metals.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/rare-metals/rare-metals-1.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/rare-metals/rare-metals-2.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/rare-metals/rare-metals-3.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/rare-metals/rare-metals-4.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/rare-metals/rare-metals-5.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/rare-metals/rare-metals-6.png",
        scale = 0.25,
        mipmap_count = 4,
      },
    },
    subgroup = "cube-smelting",
    order = "c[0-rare-metals]",
    stack_size = 100,
  },

  {
    type = "item",
    name = "cube-sand",
    icon = "__Hypercube__/graphics/sand-01.png",
    icon_size = 64,
    icon_mipmaps = 4,
    pictures = {
      {
        size = 64,
        filename = "__Hypercube__/graphics/sand-01.png",
        scale = 0.25,
        mipmap_count = 4,
      },
    },
    subgroup = "cube-experimental",
    order = "0[sand]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "cube-glass",
    icon = "__Krastorio2Assets__/icons/items/glass.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "cube-furnace",
    order = "1[a-glass]",
    stack_size = 50,
  },

  {
    type = "item",
    name = "cube-calcium",
    icon = "__Krastorio2Assets__/icons/items-with-variations/sand/sand.png",
    icon_size = 64,
    icon_mipmaps = 4,
    pictures = {
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/sand/sand.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/sand/sand-1.png",
        scale = 0.25,
        mipmap_count = 4,
      },
      {
        size = 64,
        filename = "__Krastorio2Assets__/icons/items-with-variations/sand/sand-2.png",
        scale = 0.25,
        mipmap_count = 4,
      },
    },
    subgroup = "cube-experimental",
    order = "a[calcium]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "cube-intelligent-calcium",
    icons = {
      {
        icon = "__Krastorio2Assets__/icons/items-with-variations/sand/sand.png",
        icon_size = 64, icon_mipmaps = 4,
      },
      {
        icon = "__Krastorio2Assets__/icons/items/energy-control-unit.png",
        icon_size = 64, icon_mipmaps = 4,
        scale = 0.3125, shift = {0, -4},
      },
    },
    subgroup = "cube-experimental",
    order = "a[calcium]",
    stack_size = 100,
  },
})
