data:extend({
  {
    type = "item-group",
    name = "cube-synthesis",
    order = "0",
    order_in_recipe = "0",
    icon = "__Krastorio2Assets__/technologies/matter-cube.png",
    icon_size = 256,
    icon_mipmaps = 4,
  },
  {
    type = "item-subgroup",
    name = "cube-synthesis-handling",
    group = "cube-synthesis",
    order = "0",
  },
  {
    type = "item-subgroup",
    name = "cube-synthesis-intermediates",
    group = "cube-synthesis",
    order = "1",
  },
  {
    type = "item-subgroup",
    name = "cube-synthesis-basics",
    group = "cube-synthesis",
    order = "a",
  },
  {
    type = "item-subgroup",
    name = "cube-synthesis-advanced",
    group = "cube-synthesis",
    order = "y",
  },
  {
    type = "item-subgroup",
    name = "cube-synthesis-sentience",
    group = "cube-synthesis",
    order = "z",
  },
  {
    type = "item-subgroup",
    name = "cube-smelting",
    group = "intermediate-products",
    order = "0",
  },
  {
    type = "item-subgroup",
    name = "cube-processing",
    group = "intermediate-products",
    order = "1",
  },
  {
    type = "item-subgroup",
    name = "cube-furnace",
    group = "intermediate-products",
    order = "2",
  },
  {
    type = "item-subgroup",
    name = "cube-components",
    group = "intermediate-products",
    order = "a",
  },
  {
    type = "item-subgroup",
    name = "cube-fuel",
    group = "intermediate-products",
    order = "b",
  },
  {
    type = "item-subgroup",
    name = "cube-experimental",
    group = "intermediate-products",
    order = "c",
  },
  {
    type = "item-subgroup",
    name = "cube-science",
    group = "intermediate-products",
    order = "d",
  },

  {
    type = "item-subgroup",
    name = "cube-processing-machines",
    group = "production",
    order = "y",
  },
  {
    type = "item-subgroup",
    name = "cube-production-machines",
    group = "production",
    order = "z",
  },
  {
    type = "item-subgroup",
    name = "cube-tar-input",
    group = "fluids",
    order = "f",
  },
  {
    type = "item-subgroup",
    name = "cube-tar-output",
    group = "fluids",
    order = "g",
  },
  {
    type = "item-subgroup",
    name = "cube-synthesis-fluids",
    group = "fluids",
    order = "h",
  },
})
