data:extend({
  {
    type = "recipe",
    name = "cube-offshore-pump",
    ingredients = {
      {"cube-basic-matter-unit", 40},
      {"cube-basic-motor-unit", 1},
      {"pipe", 1},
    },
    results = {{"offshore-pump", 1}},
    energy_required = 2,
    category = "cube-fabricator-handcraft",
  },
  {
    type = "recipe",
    name = "cube-boiler",
    ingredients = {
      {"cube-basic-matter-unit", 20},
      {"pipe", 4},
    },
    results = {{"cube-boiler", 1}},
    energy_required = 1,
    category = "cube-fabricator-handcraft",
  },
  {
    type = "recipe",
    name = "cube-lab",
    ingredients = {
      {"cube-basic-matter-unit", 40},
      {"cube-basic-contemplation-unit", 10},
    },
    results = {{"cube-lab", 1}},
    energy_required = 2,
    category = "cube-fabricator-handcraft",
  },
  {
    type = "recipe",
    name = "cube-steam-engine",
    ingredients = {
      {"cube-basic-matter-unit", 20},
      {"cube-basic-motor-unit", 1},
      {"pipe", 2},
    },
    results = {{"steam-engine", 1}},
    energy_required = 2,
    category = "cube-fabricator-handcraft",
  },
  {
    type = "recipe",
    name = "cube-electric-mining-drill",
    ingredients = {
      {"cube-basic-matter-unit", 120},
      {"cube-basic-motor-unit", 4},
    },
    results = {{"cube-electric-mining-drill", 1}},
    energy_required = 2,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-ultradense-furnace",
    ingredients = {
      {"stone-brick", 100},
      {"cube-basic-matter-unit", 400},
      {"cube-basic-motor-unit", 10},
      {"pipe", 20},
    },
    results = {{"cube-ultradense-furnace", 1}},
    energy_required = 10,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-electric-furnace",
    ingredients = {
      {"cube-basic-matter-unit", 100},
      {"cube-basic-motor-unit", 2},
    },
    results = {{"cube-electric-furnace", 1}},
    energy_required = 4,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-greenhouse",
    ingredients = {
      {"cube-basic-matter-unit", 200},
      {"cube-glass", 40},
      {"small-lamp", 16},
      {"wood", 20},
      {"pipe", 12},
    },
    results = {{"cube-greenhouse", 1}},
    energy_required = 4,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-crusher",
    ingredients = {
      {"cube-basic-matter-unit", 160},
      {"cube-basic-motor-unit", 8},
      {"cube-rare-metals", 40},
    },
    results = {{"cube-crusher", 1}},
    energy_required = 4,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-fabricator",
    ingredients = {
      {"cube-basic-matter-unit", 160},
      {"cube-basic-motor-unit", 4},
      {"cube-electronic-circuit", 4},
    },
    results = {{"cube-fabricator", 1}},
    energy_required = 2,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-chemical-plant",
    ingredients = {
      {"cube-basic-matter-unit", 80},
      {"cube-electronic-circuit", 4},
      {"cube-glass", 20},
      {"stone-brick", 40},
      {"pipe", 8},
    },
    results = {{"cube-chemical-plant", 1}},
    energy_required = 4,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-fluid-burner",
    ingredients = {
      {"cube-basic-matter-unit", 20},
      {"stone-brick", 20},
      {"pipe", 4},
    },
    results = {{"cube-fluid-burner", 1}},
    energy_required = 2,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-fuel-refinery",
    ingredients = {
      {"cube-basic-matter-unit", 80},
      {"cube-electronic-circuit", 2},
      {"cube-rare-metals", 40},
      {"stone-brick", 40},
      {"pipe", 8},
    },
    results = {{"cube-fuel-refinery", 1}},
    energy_required = 4,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-recovery-bay",
    ingredients = {
      {"stone-brick", 20},
      {"cube-basic-matter-unit", 250},
      {"cube-n-dimensional-widget", 5},
    },
    results = {{"cube-recovery-bay", 1}},
    energy_required = 5,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-synthesizer",
    ingredients = {
      {"stone-brick", 100},
      {"cube-basic-matter-unit", 600},
      {"cube-n-dimensional-widget", 20},
    },
    results = {{"cube-synthesizer", 1}},
    energy_required = 10,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-accumulator",
    ingredients = {
      {"cube-rare-metals", 40},
      {"cube-basic-matter-unit", 40},
    },
    results = {{"accumulator", 1}},
    energy_required = 8,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
})
