data:extend({
  {
    type = "recipe",
    name = "cube-utility-cube-manual-reboot",
    icons = {
      {
        icon = "__Krastorio2Assets__/icons/items/matter-cube.png",
        icon_size = 64, icon_mipmaps = 4,
      },
      {
        icon = "__core__/graphics/icons/tooltips/tooltip-category-debug.png",
        icon_size = 40, icon_mipmaps = 2,
        scale = 0.375, shift = {8, 8},
      },
    },
    ingredients = {
      {name = "cube-dormant-utility-cube", amount = 1, catalyst_amount = 1},
    },
    results = {
      {name = "cube-ultradense-utility-cube", amount = 1, catalyst_amount = 1},
    },
    main_product = "",
    energy_required = 10,
    category = "crafting",
    subgroup = "cube-synthesis-handling",
    order = "x[0-reboot]",
    allow_inserter_overload = false,
    allow_decomposition = false,
    allow_intermediates = false,
    allow_as_intermediate = false,
  },
  {
    type = "recipe",
    name = "cube-phantom-ultradense-constituent",
    icons = {{
      icon = "__Ultracube__/graphics/phantom-cube.png",
      icon_size = 64, icon_mipmaps = 4,
      tint = {r = 1, g = 1, b = 1, a = 0.25},
    }},
    ingredients = {{name = "cube-ultradense-utility-cube", amount = 1, catalyst_amount = 1}},
    results = {{name = "cube-phantom-ultradense-constituent", amount = 64, catalyst_amount = 64}},
    main_product = "",
    energy_required = 2,
    category = "cube-dimensionality-unpacker",
    subgroup = "cube-synthesis-phantom",
    order = "0[0-phantom]",
    always_show_made_in = true,
    allow_decomposition = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-ultradense-utility-cube-phantom",
    icons = {
      {
        icon = "__Krastorio2Assets__/icons/items/matter-cube.png",
        icon_size = 64, icon_mipmaps = 4,
      },
      {
        icon = "__Ultracube__/graphics/phantom-cube.png",
        icon_size = 64, icon_mipmaps = 4,
        scale = 0.25, shift = {8, -8},
        tint = {r = 1, g = 1, b = 1, a = 0.25},
      },
    },
    ingredients = {{name = "cube-phantom-ultradense-constituent", amount = 64, catalyst_amount = 64}},
    results = {{name = "cube-ultradense-utility-cube", amount = 1, catalyst_amount = 1}},
    main_product = "",
    energy_required = 2,
    category = "cube-dimensionality-unpacker",
    subgroup = "cube-synthesis-phantom",
    order = "0[1-phantom]",
    always_show_made_in = true,
    allow_decomposition = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-utility-cube-recharge",
    icons = {
      {
        icon = "__Krastorio2Assets__/icons/items/matter-cube.png",
        icon_size = 64, icon_mipmaps = 4,
      },
      {
        icon = "__core__/graphics/icons/technology/effect-constant/effect-constant-movement-speed.png",
        icon_size = 64, icon_mipmaps = 2,
      },
    },
    ingredients = {
      {name = "cube-dormant-utility-cube", amount = 1, catalyst_amount = 1},
    },
    results = {
      {name = "cube-ultradense-utility-cube", amount = 1, catalyst_amount = 1},
    },
    main_product = "",
    energy_required = 2,
    category = "cube-recovery-bay",
    subgroup = "cube-synthesis-handling",
    order = "x[1-recharge]",
    always_show_made_in = true,
    allow_inserter_overload = false,
    allow_decomposition = false,
    allow_intermediates = false,
    allow_as_intermediate = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-phantom-constituent-recharge",
    icons = {
      {
        icon = "__Ultracube__/graphics/phantom-cube.png",
        icon_size = 64, icon_mipmaps = 4,
        tint = {r = 1, g = 1, b = 1, a = 0.25},
      },
      {
        icon = "__core__/graphics/icons/technology/effect-constant/effect-constant-movement-speed.png",
        icon_size = 64, icon_mipmaps = 2,
      },
    },
    ingredients = {
      {name = "cube-dormant-phantom-constituent", amount = 1, catalyst_amount = 1},
    },
    results = {
      {name = "cube-phantom-ultradense-constituent", amount = 1, catalyst_amount = 1},
    },
    main_product = "",
    energy_required = 1,
    category = "cube-recovery-bay",
    subgroup = "cube-synthesis-handling",
    order = "x[2-phantom-recharge]",
    always_show_made_in = true,
    allow_inserter_overload = false,
    allow_decomposition = false,
    allow_intermediates = false,
    allow_as_intermediate = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-phantom-constituent-recharge-euphoria",
    icons = {
      {
        icon = "__Ultracube__/graphics/phantom-cube.png",
        icon_size = 64, icon_mipmaps = 4,
        tint = {r = 1, g = 1, b = 1, a = 0.25},
      },
      {
        icon = "__Ultracube__/graphics/bottled-euphoria.png",
        icon_size = 64, icon_mipmaps = 4,
        scale = 0.25, shift = {8, -8},
      },
      {
        icon = "__core__/graphics/icons/technology/effect-constant/effect-constant-movement-speed.png",
        icon_size = 64, icon_mipmaps = 2,
      },
    },
    ingredients = {
      {name = "cube-dormant-phantom-constituent", amount = 1, catalyst_amount = 1},
      {"cube-bottled-euphoria", 1},
    },
    results = {
      {name = "cube-phantom-ultradense-constituent", amount = 1, catalyst_amount = 1},
    },
    main_product = "",
    energy_required = 1,
    category = "cube-chemical-plant",
    subgroup = "cube-synthesis-phantom",
    order = "x[3-phantom-recharge]",
    always_show_made_in = true,
    allow_inserter_overload = false,
    allow_decomposition = false,
    allow_intermediates = false,
    allow_as_intermediate = false,
    enabled = false,
  },

  {
    type = "recipe",
    name = "cube-basic-matter-unit-0",
    icon = "__base__/graphics/icons/plastic-bar.png",
    icon_size = 64, icon_mipmaps = 4,
    ingredients = {
      {name = "cube-ultradense-utility-cube", amount = 1, catalyst_amount = 1},
    },
    results = {
      {name = "cube-ultradense-utility-cube", amount = 1, catalyst_amount = 1},
      {"cube-basic-matter-unit", 100},
    },
    main_product = "",
    energy_required = 1,
    category = "cube-synthesizer-handcraft",
    subgroup = "cube-synthesis-basics",
    order = "0[a-matter-0]",
    always_show_made_in = true,
    allow_decomposition = false,
  },
  {
    type = "recipe",
    name = "cube-basic-matter-unit-1",
    icons = {
      {
        icon = "__base__/graphics/icons/plastic-bar.png",
        icon_size = 64, icon_mipmaps = 4,
      },
      {
        icon = "__Krastorio2Assets__/icons/fluids/hydrogen.png",
        icon_size = 64, icon_mipmaps = 4,
        scale = 0.25, shift = {8, -8},
      },
    },
    ingredients = {
      {name = "cube-ultradense-utility-cube", amount = 1, catalyst_amount = 1},
      {type = "fluid", name = "cube-matter-replication-gel", amount = 400},
      {type = "fluid", name = "steam", amount = 2000},
    },
    results = {
      {name = "cube-ultradense-utility-cube", amount = 1, catalyst_amount = 1},
      {"cube-basic-matter-unit", 1000},
    },
    energy_required = 1,
    category = "cube-synthesizer",
    subgroup = "cube-synthesis-basics",
    order = "0[a-matter-2]",
    always_show_made_in = true,
    allow_decomposition = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-basic-matter-unit-phantom",
    icons = {
      {
        icon = "__base__/graphics/icons/plastic-bar.png",
        icon_size = 64, icon_mipmaps = 4,
      },
      {
        icon = "__Ultracube__/graphics/phantom-cube.png",
        icon_size = 64, icon_mipmaps = 4,
        scale = 0.25, shift = {8, -8},
        tint = {r = 1, g = 1, b = 1, a = 0.25},
      },
    },
    ingredients = {
      {name = "cube-phantom-ultradense-constituent", amount = 1, catalyst_amount = 1},
      {type = "fluid", name = "cube-matter-replication-gel", amount = 50},
    },
    results = {
      {name = "cube-phantom-ultradense-constituent", amount = 1, catalyst_amount = 1},
      {"cube-basic-matter-unit", 100},
    },
    main_product = "",
    energy_required = 1,
    category = "cube-synthesizer",
    subgroup = "cube-synthesis-basics",
    order = "0[a-matter-1]",
    always_show_made_in = true,
    allow_decomposition = false,
    enabled = false,
  },

  {
    type = "recipe",
    name = "cube-n-dimensional-widget-0",
    icon = "__Krastorio2Assets__/icons/items/matter-stabilizer.png",
    icon_size = 64, icon_mipmaps = 4,
    ingredients = {
      {name = "cube-ultradense-utility-cube", amount = 1, catalyst_amount = 1},
      {"cube-rare-metals", 50},
    },
    results = {
      {name = "cube-dormant-utility-cube", amount = 1, catalyst_amount = 1},
      {"cube-n-dimensional-widget", 5},
    },
    main_product = "",
    energy_required = 1,
    category = "cube-synthesizer",
    subgroup = "cube-synthesis-advanced",
    order = "0[b-widget-0]",
    always_show_made_in = true,
    allow_decomposition = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-n-dimensional-widget-1",
    icons = {
      {
        icon = "__Krastorio2Assets__/icons/items/matter-stabilizer.png",
        icon_size = 64, icon_mipmaps = 4,
      },
      {
        icon = "__Krastorio2Assets__/icons/fluids/hydrogen.png",
        icon_size = 64, icon_mipmaps = 4,
        scale = 0.25, shift = {8, -8},
      },
    },
    ingredients = {
      {name = "cube-ultradense-utility-cube", amount = 1, catalyst_amount = 1},
      {"cube-rare-metals", 200},
      {type = "fluid", name = "cube-matter-replication-gel", amount = 200},
      {type = "fluid", name = "steam", amount = 1000},
    },
    results = {
      {name = "cube-dormant-utility-cube", amount = 1, catalyst_amount = 1},
      {"cube-n-dimensional-widget", 50},
      {type = "fluid", name = "water", amount = 1000},
    },
    energy_required = 1,
    category = "cube-synthesizer",
    subgroup = "cube-synthesis-advanced",
    order = "0[b-widget-1]",
    always_show_made_in = true,
    allow_decomposition = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-phantom-components",
    icons = {
      {
        icon = "__Ultracube__/graphics/phantom-cube.png",
        icon_size = 64, icon_mipmaps = 4,
        tint = {r = 1, g = 1, b = 1, a = 0.25},
      },
      {
        icon = "__Krastorio2Assets__/icons/items/matter-stabilizer.png",
        icon_size = 64, icon_mipmaps = 4,
        scale = 0.25, shift = {8, -8},
      },
      {
        icon = "__Krastorio2Assets__/icons/items/energy-control-unit.png",
        icon_size = 64, icon_mipmaps = 4,
        scale = 0.25, shift = {8, 8},
      },
    },
    ingredients = {
      {name = "cube-phantom-ultradense-constituent", amount = 1, catalyst_amount = 1},
      {type = "fluid", name = "cube-matter-replication-gel", amount = 50},
      {type = "fluid", name = "steam", amount = 100},
      {"cube-rare-metals", 50},
      {"cube-calcium", 5},
    },
    results = {
      {name = "cube-dormant-phantom-constituent", amount = 1, catalyst_amount = 1},
      {type = "fluid", name = "water", amount = 100},
      {"cube-n-dimensional-widget", 5},
      {"cube-basic-contemplation-unit", 5},
    },
    main_product = "",
    energy_required = 1,
    category = "cube-synthesizer",
    subgroup = "cube-synthesis-advanced",
    order = "1[b-widget-contemplation]",
    always_show_made_in = true,
    allow_decomposition = false,
    enabled = false,
  },

  {
    type = "recipe",
    name = "cube-matter-replication-gel",
    icon = "__Krastorio2Assets__/icons/fluids/hydrogen.png",
    icon_size = 64, icon_mipmaps = 4,
    ingredients = {
      {"cube-basic-matter-unit", 200},
      {type = "fluid", name = "steam", amount = 8000, catalyst_amount = 2000},
      {type = "fluid", name = "water", amount = 2000, catalyst_amount = 2000},
    },
    results = {
      {type = "fluid", name = "cube-matter-replication-gel", amount = 4000},
      {type = "fluid", name = "steam", amount = 2000, catalyst_amount = 2000, temperature = 215},
      {type = "fluid", name = "water", amount = 4000, catalyst_amount = 2000},
    },
    energy_required = 4,
    category = "cube-ultradense-furnace",
    subgroup = "cube-synthesis-basics",
    order = "1[0-cube-matter-replication-gel]",
    always_show_made_in = true,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-cerebral-substrate",
    icon = "__Krastorio2Assets__/icons/fluids/matter.png",
    icon_size = 64, icon_mipmaps = 4,
    ingredients = {
      {name = "cube-dormant-utility-cube", amount = 1, catalyst_amount = 1},
      {type = "fluid", name = "cube-matter-replication-gel", amount = 400},
    },
    results = {
      {name = "cube-dormant-utility-cube", amount = 1, catalyst_amount = 1},
      {type = "fluid", name = "cube-cerebral-substrate", amount = 8000},
    },
    energy_required = 2,
    category = "cube-synthesizer",
    subgroup = "cube-synthesis-sentience",
    order = "0[cube-cerebral-substrate]",
    always_show_made_in = true,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-emotional-decomposition",
    icons = {
      {
        icon = "__Krastorio2Assets__/icons/fluids/matter.png",
        icon_size = 64, icon_mipmaps = 4,
      },
      {
        icon = "__Ultracube__/graphics/joy.png",
        icon_size = 64, icon_mipmaps = 4,
        scale = 0.275, shift = {-6, 0},
      },
      {
        icon = "__Ultracube__/graphics/despair.png",
        icon_size = 64, icon_mipmaps = 4,
        scale = 0.275, shift = {6, 0},
      }
    },
    ingredients = {
      {name = "cube-ultradense-utility-cube", amount = 1, catalyst_amount = 1},
      {type = "fluid", name = "cube-cerebral-substrate", amount = 25000},
      {type = "fluid", name = "cube-ethanol", amount = 2000},
    },
    results = {
      {name = "cube-dormant-utility-cube", amount = 1, catalyst_amount = 1},
      {type = "fluid", name = "cube-joy", amount = 10000},
      {type = "fluid", name = "cube-despair", amount = 10000},
    },
    energy_required = 4,
    category = "cube-synthesizer",
    subgroup = "cube-synthesis-sentience",
    order = "1[cube-emotional-decomposition]",
    always_show_made_in = true,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-ghost-crystal",
    icons = {{
      icon = "__Krastorio2Assets__/icons/items-with-variations/quartz/quartz.png",
      icon_size = 64, icon_mipmaps = 4,
      tint = {r = 1, g = 1, b = 1, a = 0.5},
    }},
    ingredients = {
      {name = "cube-dormant-phantom-constituent", amount = 1, catalyst_amount = 1},
      -- TODO: ???
    },
    results = {
      {name = "cube-dormant-phantom-constituent", amount = 1, catalyst_amount = 1},
      {type = "item", name = "cube-ghost-crystal", amount = 50},
    },
    main_product = "",
    energy_required = 1,
    category = "cube-synthesizer",
    subgroup = "cube-synthesis-phantom",
    order = "x[crystal]",
    always_show_made_in = true,
    allow_inserter_overload = false,
    allow_decomposition = false,
    allow_intermediates = false,
    allow_as_intermediate = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-ectoplasm",
    icon = "__Ultracube__/graphics/ectoplasm.png",
    icon_size = 64, icon_mipmaps = 4,
    ingredients = {
      {name = "cube-phantom-ultradense-constituent", amount = 1, catalyst_amount = 1},
      {type = "item", name = "cube-bottled-anguish", amount = 2, catalyst_amount = 1},
      {type = "fluid", name = "cube-unstable-gas", amount = 50},
    },
    results = {
      {name = "cube-dormant-phantom-constituent", amount = 1, catalyst_amount = 1},
      {type = "fluid", name = "cube-ectoplasm", amount = 200},
      {type = "item", name = "cube-besselheim-flask", amount = 1, probability = 0.5, catalyst_amount = 1},
    },
    main_product = "",
    energy_required = 1,
    category = "cube-synthesizer",
    subgroup = "cube-synthesis-sentience",
    order = "2[ectoplasm]",
    always_show_made_in = true,
    allow_inserter_overload = false,
    allow_decomposition = false,
    allow_intermediates = false,
    allow_as_intermediate = false,
    enabled = false,
  },
})
