data:extend({
  {
    type = "recipe",
    name = "cube-offshore-pump",
    ingredients = {
      {"cube-basic-matter-unit", 40},
      {"cube-basic-motor-unit", 1},
      {"pipe", 1},
    },
    results = {{"offshore-pump", 1}},
    energy_required = 2,
    category = "cube-fabricator-handcraft",
  },
  {
    type = "recipe",
    name = "cube-boiler",
    ingredients = {
      {"cube-basic-matter-unit", 20},
      {"pipe", 4},
    },
    results = {{"cube-boiler", 1}},
    energy_required = 1,
    category = "cube-fabricator-handcraft",
  },
  {
    type = "recipe",
    name = "cube-lab",
    ingredients = {
      {"cube-basic-matter-unit", 40},
      {"cube-basic-contemplation-unit", 10},
    },
    results = {{"cube-lab", 1}},
    energy_required = 2,
    category = "cube-fabricator-handcraft",
  },
  {
    type = "recipe",
    name = "cube-steam-engine",
    ingredients = {
      {"cube-basic-matter-unit", 20},
      {"cube-basic-motor-unit", 1},
      {"pipe", 2},
    },
    results = {{"steam-engine", 1}},
    energy_required = 2,
    category = "cube-fabricator-handcraft",
  },
  {
    type = "recipe",
    name = "cube-electric-mining-drill",
    ingredients = {
      {"cube-basic-matter-unit", 120},
      {"cube-basic-motor-unit", 10},
    },
    results = {{"cube-electric-mining-drill", 1}},
    energy_required = 2,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-ultradense-furnace",
    ingredients = {
      {"cube-basic-matter-unit", 400},
      {"cube-basic-motor-unit", 10},
      {"pipe", 20},
    },
    results = {{"cube-ultradense-furnace", 1}},
    energy_required = 10,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-fabricator",
    ingredients = {
      {"cube-basic-matter-unit", 200},
      {"cube-basic-motor-unit", 4},
      {"cube-electronic-circuit", 4},
    },
    results = {{"cube-fabricator", 1}},
    energy_required = 2,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-recovery-bay",
    ingredients = {
      {"cube-basic-matter-unit", 150},
      {"cube-semiregular-lattice", 50},
      {"cube-n-dimensional-widget", 5},
    },
    results = {{"cube-recovery-bay", 1}},
    energy_required = 5,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-synthesizer",
    ingredients = {
      {"cube-basic-matter-unit", 200},
      {"cube-semiregular-lattice", 200},
      {"cube-n-dimensional-widget", 20},
    },
    results = {{"cube-synthesizer", 1}},
    energy_required = 10,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
})
