data:extend({
  {
    type = "recipe",
    name = "cube-stone-brick",
    category = "cube-furnace",
    energy_required = 3,
    ingredients = {{"stone", 4}},
    results = {{"stone-brick", 2}},
    always_show_made_in = true,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-glass",
    category = "cube-furnace",
    energy_required = 4,
    ingredients = {{"cube-sand", 8}},
    results = {{"cube-glass", 1}},
    always_show_made_in = true,
    enabled = false,
  },

  {
    type = "recipe",
    name = "cube-rare-metals",
    icon = "__Krastorio2Assets__/icons/items-with-variations/rare-metals/rare-metals.png",
    icon_size = 64, icon_mipmaps = 4,
    ingredients = {{"cube-raw-rare-metals", 500}},
    results = {{"cube-rare-metals", 250}},
    main_product = "",
    energy_required = 4,
    category = "cube-ultradense-furnace",
    subgroup = "cube-smelting",
    order = "0[0-rare-metal-smelting]",
    always_show_made_in = true,
    always_show_products = true,
    show_amount_in_title = false,
    allow_decomposition = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-refined-rare-metals",
    icons = {
      {
        icon = "__Krastorio2Assets__/icons/items-with-variations/rare-metals/rare-metals.png",
        icon_size = 64, icon_mipmaps = 4,
      },
      {
        icon = "__Krastorio2Assets__/icons/items-with-variations/enriched-rare-metals/enriched-rare-metals.png",
        icon_size = 64, icon_mipmaps = 4,
        scale = 0.25, shift = {8, -8},
      },
    },
    ingredients = {{"cube-refined-rare-metals", 250}},
    results = {{"cube-rare-metals", 500}},
    main_product = "",
    energy_required = 4,
    category = "cube-ultradense-furnace",
    subgroup = "cube-smelting",
    order = "0[1-refined-rate-metal-smelting]",
    always_show_made_in = true,
    always_show_products = true,
    show_amount_in_title = false,
    allow_decomposition = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-rare-metal-crushing",
    icon = "__Krastorio2Assets__/icons/items-with-variations/enriched-rare-metals/enriched-rare-metals.png",
    icon_size = 64, icon_mipmaps = 4,
    ingredients = {{"cube-raw-rare-metals", 20}},
    results = {
      {type = "item", name = "cube-refined-rare-metals", amount_min = 10, amount_max = 20},
      {type = "item", name = "cube-calcium", amount_min = 0, amount_max = 10},
      {type = "item", name = "stone", amount_min = 0, amount_max = 5},
    },
    energy_required = 4,
    category = "cube-crusher",
    subgroup = "cube-processing",
    order = "c[rare-metal-crushing]",
    always_show_made_in = true,
    always_show_products = true,
    show_amount_in_title = false,
    allow_decomposition = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-stone-crushing",
    ingredients = {{"stone", 8}},
    results = {{"cube-sand", 16}},
    energy_required = 4,
    category = "cube-crusher",
    subgroup = "cube-processing",
    order = "d[stone-crushing]",
    always_show_made_in = true,
    always_show_products = true,
    show_amount_in_title = false,
    allow_decomposition = true,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-sand-dilution",
    icons = {
      {
        icon_size = 64, icon_mipmaps = 4,
        icon = "__Ultracube__/graphics/sand-01.png",
      },
      {
        icon_size = 64, icon_mipmaps = 4,
        icon = "__Krastorio2Assets__/icons/fluids/water.png",
        scale = 0.3125, shift = {0, -4},
      },
    },
    ingredients = {
      {type = "fluid", name = "water", amount = 200, catalyst_amount = 200},
      {"cube-sand", 4},
    },
    results = {{type = "fluid", name = "water", amount = 240, catalyst_amount = 200}},
    energy_required = 4,
    category = "cube-chemical-plant",
    subgroup = "cube-experimental",
    order = "0[sand-recycling]",
    main_product = "",
    always_show_made_in = true,
    always_show_products = true,
    show_amount_in_title = false,
    allow_decomposition = false,
    enabled = false,
  },

  {
    type = "recipe",
    name = "cube-greenhouse-wood",
    icon = "__base__/graphics/icons/wood.png",
    icon_size = 64, icon_mipmaps = 4,
    ingredients = {
      {type = "fluid", name = "water", amount = 400},
    },
    results = {{"wood", 60}},
    energy_required = 60,
    main_product = "",
    category = "cube-greenhouse",
    subgroup = "cube-fuel",
    order = "0[wood]",
    always_show_made_in = true,
    allow_decomposition = false,
    enabled = false,
  },
})
