data:extend({
  {
    type = "recipe",
    name = "cube-utility-cube-manual-reboot",
    icon = "__Krastorio2Assets__/icons/items/matter-cube.png",
    icon_size = 64,
    icon_mipmaps = 4,
    ingredients = {{"cube-dormant-utility-cube", 1}},
    results = {{"cube-ultradense-utility-cube", 1}},
    main_product = "",
    energy_required = 10,
    category = "crafting",
    subgroup = "cube-cubes",
    order = "0[0-cube]",
    allow_inserter_overload = false,
    allow_decomposition = false,
    allow_intermediates = false,
    allow_as_intermediate = false,
  },
  {
    type = "recipe",
    name = "cube-utility-cube-recharge",
    icon = "__Krastorio2Assets__/icons/items/matter-cube.png",
    icon_size = 64,
    icon_mipmaps = 4,
    ingredients = {{"cube-dormant-utility-cube", 1}},
    results = {{"cube-ultradense-utility-cube", 1}},
    main_product = "",
    energy_required = 2,
    category = "cube-recovery-bay",
    subgroup = "cube-cubes",
    order = "0[1-cube]",
    always_show_made_in = true,
    allow_inserter_overload = false,
    allow_decomposition = false,
    allow_intermediates = false,
    allow_as_intermediate = false,
    enabled = false,
  },

  {
    type = "recipe",
    name = "cube-basic-matter-unit-0",
    ingredients = {{"cube-ultradense-utility-cube", 1}},
    results = {
      {"cube-ultradense-utility-cube", 1},
      {"cube-basic-matter-unit", 100},
    },
    main_product = "cube-basic-matter-unit",
    energy_required = 1,
    category = "cube-synthesizer-handcraft",
    always_show_made_in = true,
    allow_decomposition = false,
  },
  {
    type = "recipe",
    name = "cube-basic-matter-unit-1",
    icons = {
      {
        icon = "__base__/graphics/icons/plastic-bar.png",
        icon_size = 64, icon_mipmaps = 4,
      },
      {
        icon = "__base__/graphics/icons/fluid/steam.png",
        icon_size = 64, icon_mipmaps = 4,
        scale = 0.375, shift = {6, -6},
      }
    },
    ingredients = {
      {"cube-ultradense-utility-cube", 1},
      {"cube-basic-matter-unit", 1},
      {type = "fluid", name = "cube-matter-duplication-gel", amount = 200},
      {type = "fluid", name = "steam", amount = "500"},
    },
    results = {
      {"cube-dormant-utility-cube", 1},
      {"cube-basic-matter-unit", 1000},
    },
    energy_required = 1,
    category = "cube-synthesizer",
    subgroup = "cube-basics",
    order = "0[a-matter-1]",
    always_show_made_in = true,
    allow_decomposition = false,
    enabled = false,
  },

  {
    type = "recipe",
    name = "cube-n-dimensional-widget-0",
    ingredients = {
      {"cube-ultradense-utility-cube", 1},
      {"cube-rare-metals", 50},
    },
    results = {
      {"cube-dormant-utility-cube", 1},
      {"cube-n-dimensional-widget", 5},
    },
    main_product = "cube-n-dimensional-widget",
    energy_required = 1,
    category = "cube-synthesizer",
    always_show_made_in = true,
    allow_decomposition = false,
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-n-dimensional-widget-1",
    icons = {
      {
        icon = "__Krastorio2Assets__/icons/items/matter-stabilizer.png",
        icon_size = 64, icon_mipmaps = 4,
      },
      {
        icon = "__base__/graphics/icons/fluid/steam.png",
        icon_size = 64, icon_mipmaps = 4,
        scale = 0.375, shift = {6, -6},
      }
    },
    ingredients = {
      {"cube-ultradense-utility-cube", 1},
      {"cube-rare-metals", 500},
      {"cube-n-dimensional-widget", 50},
      {type = "fluid", name = "cube-matter-duplication-gel", amount = 500},
      {type = "fluid", name = "steam", amount = "500"},
    },
    results = {
      {"cube-dormant-utility-cube", 1},
      {"cube-n-dimensional-widget", 100},
    },
    energy_required = 1,
    category = "cube-synthesizer",
    subgroup = "cube-basics",
    order = "0[b-widget-1]",
    always_show_made_in = true,
    allow_decomposition = false,
    enabled = false,
  },

  {
    type = "recipe",
    name = "cube-rare-metals",
    ingredients = {{"cube-raw-rare-metals", 500}},
    results = {{"cube-rare-metals", 250}},
    energy_required = 4,
    category = "cube-ultradense-furnace",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-conductive-wire",
    ingredients = {{"cube-rare-metals", 2}},
    results = {{"copper-cable", 4}},
    energy_required = 1,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-electronic-circuit",
    ingredients = {
      {"cube-basic-matter-unit", 2},
      {"cube-rare-metals", 1},
      {"copper-cable", 1},
    },
    results = {{"cube-electronic-circuit", 1}},
    energy_required = 1,
    category = "cube-fabricator-handcraft",
    enabled = false,
  },
  {
    type = "recipe",
    name = "cube-basic-motor-unit",
    ingredients = {
      {"pipe", 2},
      {"cube-basic-matter-unit", 4},
    },
    results = {{"cube-basic-motor-unit", 1}},
    energy_required = 2,
    category = "cube-fabricator-handcraft",
  },
  {
    type = "recipe",
    name = "cube-semiregular-lattice",
    ingredients = {{"cube-basic-matter-unit", 500}},
    results = {{"cube-semiregular-lattice", 250}},
    energy_required = 15,
    category = "cube-fabricator-handcraft",
  },
  {
    type = "recipe",
    name = "cube-intelligent-calcium",
    ingredients = {
      {"cube-calcium", 2},
      {"cube-basic-contemplation-unit", 1},
      {type = "fluid", name = "steam", amount = 100},
    },
    results = {{"cube-intelligent-calcium", 1}},
    energy_required = 1,
    category = "cube-fabricator",
  },

  {
    type = "recipe",
    name = "cube-matter-duplication-gel",
    ingredients = {
      {"cube-ultradense-utility-cube", 1},
      {"cube-basic-matter-unit", 100},
      {type = "fluid", name = "steam", amount = 1000, catalyst_amount = 500},
      {type = "fluid", name = "water", amount = 500, catalyst_amount = 500},
    },
    results = {
      {"cube-dormant-utility-cube", 1},
      {type = "fluid", name = "cube-matter-duplication-gel", amount = 1000},
      {type = "fluid", name = "steam", amount = 500, catalyst_amount = 500},
      {type = "fluid", name = "water", amount = 1000, catalyst_amount = 500},
    },
    main_product = "cube-matter-duplication-gel",
    energy_required = 2,
    category = "cube-ultradense-furnace",
    always_show_made_in = true,
    enabled = false,
  },
})
