require("__base__/prototypes/entity/combinator-pictures")

data:extend({
  {
    type = "item-subgroup",
    name = "cube-mechanical-network",
    group = "intermediate-products",
    order = "z",
  },
  {
    type = "item-subgroup",
    name = "cube-mechanical-network-gates",
    group = "logistics",
    order = "hh"
  },

  {
    type = "item",
    name = "cube-mechanical-network-bit-0",
    icon = "__base__/graphics/icons/signal/signal_0.png",
    icon_size = 64, icon_mipmaps = 4,
    flags = {"hidden", "not-stackable"},
    subgroup = "cube-mechanical-network",
    order = "0[0]",
    stack_size = 1,
  },
  {
    type = "item",
    name = "cube-mechanical-network-bit-1",
    icon = "__base__/graphics/icons/signal/signal_1.png",
    icon_size = 64, icon_mipmaps = 4,
    flags = {"hidden", "not-stackable"},
    subgroup = "cube-mechanical-network",
    order = "0[0]",
    stack_size = 1,
  },

  {
    type = "item",
    name = "cube-mechanical-network-source",
    icon = "__base__/graphics/icons/constant-combinator.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-mechanical-network-gates",
    order = "0[source]",
    place_result = "cube-mechanical-network-source",
    stack_size = 50,
  },
  {
    type = "item",
    name = "cube-mechanical-network-sink",
    icon = "__base__/graphics/icons/constant-combinator.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-mechanical-network-gates",
    order = "1[sink]",
    place_result = "cube-mechanical-network-sink",
    stack_size = 50,
  },
  {
    type = "item",
    name = "cube-mechanical-network-not-gate",
    icon = "__base__/graphics/icons/constant-combinator.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-mechanical-network-gates",
    order = "2[not-gate]",
    place_result = "cube-mechanical-network-not-gate",
    stack_size = 50,
  },
  {
    type = "item",
    name = "cube-mechanical-network-and-gate",
    icon = "__base__/graphics/icons/decider-combinator.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-mechanical-network-gates",
    order = "3[and-gate]",
    place_result = "cube-mechanical-network-and-gate",
    stack_size = 50,
  },
  {
    type = "item",
    name = "cube-mechanical-network-or-gate",
    icon = "__base__/graphics/icons/decider-combinator.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-mechanical-network-gates",
    order = "4[or-gate]",
    place_result = "cube-mechanical-network-or-gate",
    stack_size = 50,
  },
  {
    type = "item",
    name = "cube-mechanical-network-xor-gate",
    icon = "__base__/graphics/icons/decider-combinator.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "cube-mechanical-network-gates",
    order = "5[xor-gate]",
    place_result = "cube-mechanical-network-xor-gate",
    stack_size = 50,
  },

  {
    type = "recipe-category",
    name = "cube-mechanical-network-source",
    order = "z-00",
  },
  {
    type = "recipe-category",
    name = "cube-mechanical-network-sink",
    order = "z-01",
  },
  {
    type = "recipe-category",
    name = "cube-mechanical-network-not-gate",
    order = "z-02",
  },
  {
    type = "recipe-category",
    name = "cube-mechanical-network-and-gate",
    order = "z-10",
  },
  {
    type = "recipe-category",
    name = "cube-mechanical-network-and-gate-0",
    order = "z-100",
  },
  {
    type = "recipe-category",
    name = "cube-mechanical-network-and-gate-1",
    order = "z-101",
  },
  {
    type = "recipe-category",
    name = "cube-mechanical-network-or-gate",
    order = "z-11",
  },
  {
    type = "recipe-category",
    name = "cube-mechanical-network-or-gate-0",
    order = "z-110",
  },
  {
    type = "recipe-category",
    name = "cube-mechanical-network-or-gate-1",
    order = "z-111",
  },
  {
    type = "recipe-category",
    name = "cube-mechanical-network-xor-gate",
    order = "z-12",
  },
  {
    type = "recipe-category",
    name = "cube-mechanical-network-xor-gate-0",
    order = "z-120",
  },
  {
    type = "recipe-category",
    name = "cube-mechanical-network-xor-gate-1",
    order = "z-121",
  },

  {
    type = "recipe",
    name = "cube-mechanical-network-source-0",
    ingredients = {},
    results = {{"cube-mechanical-network-bit-0", 1}},
    energy_required = 1,
    category = "cube-mechanical-network-source",
    subgroup = "cube-mechanical-network",
    order = "0[source-0]",
    hidden = true,
    hidden_from_player_crafting = true,
  },

  {
    type = "recipe",
    name = "cube-mechanical-network-sink-0",
    icon = "__base__/graphics/icons/signal/signal_0.png",
    icon_size = 64, icon_mipmaps = 4,
    ingredients = {{"cube-mechanical-network-bit-0", 1}},
    results = {},
    energy_required = 0.5,
    category = "cube-mechanical-network-sink",
    subgroup = "cube-mechanical-network",
    order = "0[sink-0]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-sink-1",
    icon = "__base__/graphics/icons/signal/signal_1.png",
    icon_size = 64, icon_mipmaps = 4,
    ingredients = {{"cube-mechanical-network-bit-1", 1}},
    results = {},
    energy_required = 0.5,
    category = "cube-mechanical-network-sink",
    subgroup = "cube-mechanical-network",
    order = "0[sink-1]",
    hidden = true,
    hidden_from_player_crafting = true,
  },

  {
    type = "recipe",
    name = "cube-mechanical-network-not-gate-0",
    ingredients = {{"cube-mechanical-network-bit-0", 1}},
    results = {{"cube-mechanical-network-bit-1", 1}},
    energy_required = 0.5,
    category = "cube-mechanical-network-not-gate",
    subgroup = "cube-mechanical-network",
    order = "0[not-gate-0]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-not-gate-1",
    ingredients = {{"cube-mechanical-network-bit-1", 1}},
    results = {{"cube-mechanical-network-bit-0", 1}},
    energy_required = 0.5,
    category = "cube-mechanical-network-not-gate",
    subgroup = "cube-mechanical-network",
    order = "0[not-gate-1]",
    hidden = true,
    hidden_from_player_crafting = true,
  },

  {
    type = "recipe",
    name = "cube-mechanical-network-and-gate-0",
    ingredients = {{"cube-mechanical-network-bit-0", 2}},
    results = {{"cube-mechanical-network-bit-0", 1}},
    energy_required = 60,
    category = "cube-mechanical-network-and-gate",
    subgroup = "cube-mechanical-network",
    order = "0[and-gate-0]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-and-gate-1",
    ingredients = {{"cube-mechanical-network-bit-1", 2}},
    results = {{"cube-mechanical-network-bit-1", 1}},
    energy_required = 60,
    category = "cube-mechanical-network-and-gate",
    subgroup = "cube-mechanical-network",
    order = "0[and-gate-1]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-and-gate-00",
    ingredients = {{"cube-mechanical-network-bit-0", 1}},
    results = {{"cube-mechanical-network-bit-0", 1}},
    energy_required = 0.5,
    category = "cube-mechanical-network-and-gate-0",
    subgroup = "cube-mechanical-network",
    order = "0[and-gate-00]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-and-gate-01",
    ingredients = {{"cube-mechanical-network-bit-1", 1}},
    results = {{"cube-mechanical-network-bit-0", 1}},
    energy_required = 0.5,
    category = "cube-mechanical-network-and-gate-0",
    subgroup = "cube-mechanical-network",
    order = "0[and-gate-01]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-and-gate-10",
    ingredients = {{"cube-mechanical-network-bit-0", 1}},
    results = {{"cube-mechanical-network-bit-0", 1}},
    energy_required = 0.5,
    category = "cube-mechanical-network-and-gate-1",
    subgroup = "cube-mechanical-network",
    order = "0[and-gate-01]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-and-gate-11",
    ingredients = {{"cube-mechanical-network-bit-1", 1}},
    results = {{"cube-mechanical-network-bit-1", 1}},
    energy_required = 0.5,
    category = "cube-mechanical-network-and-gate-1",
    subgroup = "cube-mechanical-network",
    order = "0[and-gate-11]",
    hidden = true,
    hidden_from_player_crafting = true,
  },

  {
    type = "recipe",
    name = "cube-mechanical-network-or-gate-0",
    ingredients = {{"cube-mechanical-network-bit-0", 2}},
    results = {{"cube-mechanical-network-bit-0", 1}},
    energy_required = 60,
    category = "cube-mechanical-network-or-gate",
    subgroup = "cube-mechanical-network",
    order = "0[or-gate-0]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-or-gate-1",
    ingredients = {{"cube-mechanical-network-bit-1", 2}},
    results = {{"cube-mechanical-network-bit-1", 1}},
    energy_required = 60,
    category = "cube-mechanical-network-or-gate",
    subgroup = "cube-mechanical-network",
    order = "0[or-gate-1]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-or-gate-00",
    ingredients = {{"cube-mechanical-network-bit-0", 1}},
    results = {{"cube-mechanical-network-bit-0", 1}},
    energy_required = 0.5,
    category = "cube-mechanical-network-or-gate-0",
    subgroup = "cube-mechanical-network",
    order = "0[or-gate-00]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-or-gate-01",
    ingredients = {{"cube-mechanical-network-bit-1", 1}},
    results = {{"cube-mechanical-network-bit-1", 1}},
    energy_required = 0.5,
    category = "cube-mechanical-network-or-gate-0",
    subgroup = "cube-mechanical-network",
    order = "0[or-gate-01]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-or-gate-10",
    ingredients = {{"cube-mechanical-network-bit-0", 1}},
    results = {{"cube-mechanical-network-bit-1", 1}},
    energy_required = 0.5,
    category = "cube-mechanical-network-or-gate-1",
    subgroup = "cube-mechanical-network",
    order = "0[or-gate-01]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-or-gate-11",
    ingredients = {{"cube-mechanical-network-bit-1", 1}},
    results = {{"cube-mechanical-network-bit-1", 1}},
    energy_required = 0.5,
    category = "cube-mechanical-network-or-gate-1",
    subgroup = "cube-mechanical-network",
    order = "0[or-gate-11]",
    hidden = true,
    hidden_from_player_crafting = true,
  },

  {
    type = "recipe",
    name = "cube-mechanical-network-xor-gate-0",
    ingredients = {{"cube-mechanical-network-bit-0", 2}},
    results = {{"cube-mechanical-network-bit-0", 1}},
    energy_required = 60,
    category = "cube-mechanical-network-xor-gate",
    subgroup = "cube-mechanical-network",
    order = "0[xor-gate-0]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-xor-gate-1",
    ingredients = {{"cube-mechanical-network-bit-1", 2}},
    results = {{"cube-mechanical-network-bit-1", 1}},
    energy_required = 60,
    category = "cube-mechanical-network-xor-gate",
    subgroup = "cube-mechanical-network",
    order = "0[xor-gate-1]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-xor-gate-00",
    ingredients = {{"cube-mechanical-network-bit-0", 1}},
    results = {{"cube-mechanical-network-bit-0", 1}},
    energy_required = 0.5,
    category = "cube-mechanical-network-xor-gate-0",
    subgroup = "cube-mechanical-network",
    order = "0[xor-gate-00]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-xor-gate-01",
    ingredients = {{"cube-mechanical-network-bit-1", 1}},
    results = {{"cube-mechanical-network-bit-1", 1}},
    energy_required = 0.5,
    category = "cube-mechanical-network-xor-gate-0",
    subgroup = "cube-mechanical-network",
    order = "0[xor-gate-01]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-xor-gate-10",
    ingredients = {{"cube-mechanical-network-bit-0", 1}},
    results = {{"cube-mechanical-network-bit-1", 1}},
    energy_required = 0.5,
    category = "cube-mechanical-network-xor-gate-1",
    subgroup = "cube-mechanical-network",
    order = "0[xor-gate-01]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
  {
    type = "recipe",
    name = "cube-mechanical-network-xor-gate-11",
    ingredients = {{"cube-mechanical-network-bit-1", 1}},
    results = {{"cube-mechanical-network-bit-1", 0}},
    energy_required = 0.5,
    category = "cube-mechanical-network-xor-gate-1",
    subgroup = "cube-mechanical-network",
    order = "0[xor-gate-11]",
    hidden = true,
    hidden_from_player_crafting = true,
  },
})